### ISSUE TITLE
Crash with exception

### ISSUE THREAD

**Issue by djdookie** [djdookie/Advisor#11]
Got the following exception today while playing against hunter.

`System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at HDT.Plugins.Advisor.Advisor.<UpdateCardList>d__20.MoveNext() in D:\TfsProj\Advisor\Advisor\Advisor.cs:line 249
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by djdookie** [comment]
The reason was erroneous data from MetaStats. We got duplicate decks here:
http://metastats.net/deck/53301f91-caae-4fe2-aa2d-aa753d527b22/last7/
I reported the issue to MetaStats.

Fixed in 0581c9f by filtering duplicate decks.

**Comment by Heelythegreat** [comment]
Hi,

I'm getting the same issue. Also against hunter.

When can we expect a release to fix it?

**Comment by djdookie** [comment]
I will try to release at the weekend.
Delete and re-import the archetype decks. Metastats fixed the data yesterday, so the current problem shouldn't occur anymore, even without the fix.

**Comment by djdookie** [comment]
The bug was fixed with release v1.0.4.
Have fun! ;)
