### ISSUE TITLE
Advisor Crash HDT new versión (Edit:Solved)

### ISSUE THREAD

**Issue by Medianero** [djdookie/Advisor#18]
Advisor v1.0.7  Crash HDT new versión 

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Max(IEnumerable`1 source)
   at HDT.Plugins.Advisor.Advisor.<UpdateCardList>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Medianero** [comment]
Sorry ... newbies fail. Solved. 
Just start HDT and turn on plugin with HS closed, then just remove old archetype decks and import the new ones.

**Comment by Nym132** [comment]
I'm getting this issue as well. I've tried importing new ones but it doesn't work for me. It crashes when I spectate somebody

**Comment by djdookie** [comment]
I was finally able to locate and solve this problem.
Thanks for your reports!

This is fixed with commit ce34b4e26582dad4d9ec6b5ecec1a2cefef8a26e and will be fixed with the next release soon.

As a workaround until release you could unselect practice and/or wild modes in the Advisor settings, because the crash should only appear here.

**Comment by djdookie** [comment]
Fixed with Release v1.0.8: https://github.com/djdookie/Advisor/releases/tag/v1.0.8
